apiVersion: v1
kind: Service
metadata:
  name: discovery-svc
  namespace: pubsub-demo
  labels:
    app: discovery
spec:
  selector:
    app: discovery
  ports:
    - protocol: TCP
      port: 5555        # Service port
      targetPort: 5555  # Container port
