apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: pubsub-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      initContainers: # Add this section
        - name: configure-dns # Name for the init container
          image: busybox:latest # A lightweight image with shell utilities
          command: ['sh', '-c']
          args:
            - |
              echo "nameserver 8.8.8.8" > /etc/resolv.conf
              cat /etc/resolv.conf
      containers:
        - name: subscriber
          image: ghcr.io/d-zg/pubsub:latest
          env:
            - name: DISCOVERY_ADDRESS
              value: "discovery-svc:5555"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["python3", "SubscriberAppln.py"]
          args:
            - "-d"
            - "discovery-svc:5555"
            - "-n"
            - "sub$(POD_NAME)"
            - "-T"
            - "2"
            - "-l"
            - "10"
      volumes:
        - name: config-volume
          configMap:
            name: pubsub-config
