apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: pubsub-demo
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.96.0.10
      - 8.8.8.8
    searches:
      - pubsub-demo.svc.cluster.local
      - svc.cluster.local
      - cluster.local
  containers:
    - name: debug
      image: nicolaka/netshoot
      command: ["/bin/bash"]
      tty: true
