apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: pubsub-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: ghcr.io/d-zg/pubsub:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DISCOVERY_ADDRESS
              value: "discovery-svc:5555"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["python3", "PublisherAppln.py"]
          args:
            - "-d"
            - "discovery-svc:5555"
            - "-n"
            - "pub$(POD_NAME)"
            - "-p"
            - "5556"
            - "-T"
            - "2"
            - "-l"
            - "10"
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: pubsub-config
