apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: pubsub-demo
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181        # Service port
      targetPort: 2181  # Container port
